### ISSUE TITLE
感谢您的写的众多lsq工具和分享

### ISSUE THREAD

**Issue by qbosen** [pengx17/knowledge-garden#1]
感谢您的写的众多lsq插件和工具，新的publish工具也非常有用。 这里有一个小的格式问题 

![image](https://user-images.githubusercontent.com/15816040/148480559-f005e36c-9987-4111-ba4a-cb450a34252d.png)

**Comment by pengx17** [comment]
已修复! 谢谢你的称赞，我很高兴能帮助到你和Logseq社区
