### ISSUE TITLE
auto commit 失败

### ISSUE THREAD

**Issue by ygr99** [pengx17/knowledge-garden#4]
auto commit 失败
![](https://wangguanjingji.oss-cn-beijing.aliyuncs.com/picture/1654142924064.png)

**Comment by pengx17** [comment]
请试试 https://github.com/pengx17/knowledge-garden/commit/c3f7ad812ba58f26ee3d6daafcdb889deff90aa1 
估计是 Logseq 本身有的改动导致 publish 脚本失效了

**Comment by ygr99** [comment]
非常感谢！
